### ISSUE TITLE
Error; code: 'ERR_DLOPEN_FAILED'

### ISSUE THREAD

**Issue by ika9810** [ika9810/Danhocats-Daily#1]
Run npm run build

> hashlips_art_engine@1.1.1 build /home/runner/work/Danhocats-Daily/Danhocats-Daily
> node index.js

internal/modules/cjs/loader.js:11[4](https://github.com/ika9810/Danhocats-Daily/actions/runs/4905015819/jobs/8758528698#step:4:5)4
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /home/runner/work/Danhocats-Daily/Danhocats-Daily/node_modules/canvas/build/Release/canvas.node: invalid ELF header
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:9[5](https://github.com/ika9810/Danhocats-Daily/actions/runs/4905015819/jobs/8758528698#step:4:6)0:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/runner/work/Danhocats-Daily/Danhocats-Daily/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
  code: 'ERR_DLOPEN_FAILED'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hashlips_art_engine@1.1.1 build: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hashlips_art_engine@1.1.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2023-05-07T03_0[6](https://github.com/ika9810/Danhocats-Daily/actions/runs/4905015819/jobs/8758528698#step:4:7)_03_405Z-debug.log
Error: Process completed with exit code 1.

**Comment by ika9810** [comment]
Fixed with Adding
"npm i"

reference : https://github.com/vercel/pkg/issues/1448
